const mockMediumSpaces = [ 
  { id: 320, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 350, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 390, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 317, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 357, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 387, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 325, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 355, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 385, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 318, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 349, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 389, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 316, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 326, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 356, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 386, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 322, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 352, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 382, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 324, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 354, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 384, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 319, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 358, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 388, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 321, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 323, row: 2, size: 'medium', level: 1, vehicle_id: null },
  { id: 383, row: 10, size: 'medium', level: 3, vehicle_id: null },
  { id: 351, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 353, row: 6, size: 'medium', level: 2, vehicle_id: null },
  { id: 381, row: 10, size: 'medium', level: 3, vehicle_id: null } 
];

module.exports = mockMediumSpaces;