const mockLargeSpaces = [ 
  [ { id: 400, row: 2, size: 'large', level: 3, vehicle_id: null },
   { id: 397, row: 2, size: 'large', level: 3, vehicle_id: null },
   { id: 399, row: 2, size: 'large', level: 3, vehicle_id: null },
   { id: 396, row: 2, size: 'large', level: 3, vehicle_id: null },
   { id: 398, row: 2, size: 'large', level: 3, vehicle_id: null } ],
  [ { id: 330, row: 3, size: 'large', level: 1, vehicle_id: null },
   { id: 327, row: 3, size: 'large', level: 1, vehicle_id: null },
   { id: 328, row: 3, size: 'large', level: 1, vehicle_id: null },
   { id: 329, row: 3, size: 'large', level: 1, vehicle_id: null },
   { id: 331, row: 3, size: 'large', level: 1, vehicle_id: null } ],
  [ { id: 335, row: 4, size: 'large', level: 1, vehicle_id: null },
   { id: 336, row: 4, size: 'large', level: 1, vehicle_id: null },
   { id: 332, row: 4, size: 'large', level: 1, vehicle_id: null },
   { id: 334, row: 4, size: 'large', level: 1, vehicle_id: null },
   { id: 333, row: 4, size: 'large', level: 1, vehicle_id: null } ],
  [ { id: 360, row: 7, size: 'large', level: 2, vehicle_id: null },
   { id: 359, row: 7, size: 'large', level: 2, vehicle_id: null },
   { id: 362, row: 7, size: 'large', level: 2, vehicle_id: null },
   { id: 361, row: 7, size: 'large', level: 2, vehicle_id: null },
   { id: 363, row: 7, size: 'large', level: 2, vehicle_id: null } ],
  [ { id: 367, row: 8, size: 'large', level: 2, vehicle_id: null },
   { id: 365, row: 8, size: 'large', level: 2, vehicle_id: null },
   { id: 366, row: 8, size: 'large', level: 2, vehicle_id: null },
   { id: 364, row: 8, size: 'large', level: 2, vehicle_id: null },
   { id: 368, row: 8, size: 'large', level: 2, vehicle_id: null } ],
  [ { id: 395, row: 11, size: 'large', level: 3, vehicle_id: null },
   { id: 392, row: 11, size: 'large', level: 3, vehicle_id: null },
   { id: 394, row: 11, size: 'large', level: 3, vehicle_id: null },
   { id: 391, row: 11, size: 'large', level: 3, vehicle_id: null },
   { id: 393, row: 11, size: 'large', level: 3, vehicle_id: null } ] 
];


module.exports = mockLargeSpaces;